//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karambolo.Extensions.Logging.File.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karambolo.Extensions.Logging.File.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log entry &apos;{0}&apos; created at {1} was dropped because the queue of log file &quot;{2}&quot; was full..
        /// </summary>
        internal static string DiagnosticEvent_LogEntryDropped {
            get {
                return ResourceManager.GetString("DiagnosticEvent_LogEntryDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing log entry &apos;{0}&apos; created at {1} to log file &quot;{2}&quot; failed. {3}.
        /// </summary>
        internal static string DiagnosticEvent_LogEntryWriteFailed {
            get {
                return ResourceManager.GetString("DiagnosticEvent_LogEntryWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file queues were not completed within the allowed time limit. Forcing completion..
        /// </summary>
        internal static string DiagnosticEvent_QueuesCompletionForced {
            get {
                return ResourceManager.GetString("DiagnosticEvent_QueuesCompletionForced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inheritors of &apos;{0}&apos; must override the &apos;{1}&apos; method and provide an implementation that creates a clone of the subclass instance..
        /// </summary>
        internal static string ExtendedOptionsCloneNotDefined {
            get {
                return ResourceManager.GetString("ExtendedOptionsCloneNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must implement the &apos;{0}&apos; interface..
        /// </summary>
        internal static string InterfaceNotImplemented {
            get {
                return ResourceManager.GetString("InterfaceNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must provide a parameterless constructor..
        /// </summary>
        internal static string ParameterlessCtorNotProvided {
            get {
                return ResourceManager.GetString("ParameterlessCtorNotProvided", resourceCulture);
            }
        }
    }
}
